`array`: Creates a NumPy array from a given list.

`copy:` Creates a deep copy of the array.

`view:` Creates a new view of the array with the same data.

`ndim:` Returns the number of dimensions of the array.

`astype`: Changes the data type of the array.

`reshape`: Returns a new array with a modified shape.

`dtypes`: Accesses the data type of the array elements.

In [ ]:
# 1
bunda array yarat [2, 4, 6, 8, 10,15].

In [1]:
import numpy as np

In [15]:
arr = np.array([2, 4, 6, 8, 10,15])
print(arr)


[ 2  4  6  8 10 15]


In [ ]:
# 2 
hemin array in 1 ci indexi 5 ile deyis sonra 1 element daha elave et array e

In [16]:
arr[0]=5
arr = np.append(arr,24)
print('Element elave etdikden sonra: ',arr)

Element elave etdikden sonra:  [ 5  4  6  8 10 15 24]


In [ ]:
# 3
hemin array`in kopyasini yarat

In [17]:
arr1 = np.copy(arr)
print('Kopya: ',arr1)

Kopya:  [ 5  4  6  8 10 15 24]


In [ ]:
# 4 
hemin arrayin sadece 4,5,6 ya qeder olan hissesinin kopyasini yarat

In [18]:
arr2 = np.copy(arr[:3])
print(arr2)

[5 4 6]


In [ ]:
# 5
Hemin arrayin view`nu yarat

In [20]:
arr_view = arr
print(arr_view)

[ 5  4  6  8 10 15 24]


In [ ]:
# 6 
hemin arrayi i 3x2 reshape et shape ni goster ve herhansi bir deyere assign et

In [37]:
arr = np.array([2, 4, 6, 8, 10,15])
arr_reshape = arr.reshape(3,2)
print('Reshape edildi \n',arr_reshape)
arr_reshape[2,1]=12
print('Element deyer assign \n',arr_reshape)

Reshape edildi 
 [[ 2  4]
 [ 6  8]
 [10 15]]
Element deyer assign 
 [[ 2  4]
 [ 6  8]
 [10 12]]


In [ ]:
# 7 
assign olunmus array i evvelki halina qaytar

In [38]:
arr_orig = arr_reshape.reshape(-1)
print(arr_orig)

[ 2  4  6  8 10 12]


In [ ]:
# 8 
ilk yaradilan array`i print et sadece siralama 1+ artsin yeni 2,6,10 kimi

In [41]:
arr = np.array([2, 4, 6, 8, 10,15])
print(arr)
arr[::2]

[ 2  4  6  8 10 15]


array([ 2,  6, 10])

In [ ]:
# 9 
array in dtype ni goster ve sonrasinda onu float olaraq deyis

In [48]:
arr.dtype

arr = arr.astype('float')
arr.dtype

dtype('float64')

In [ ]:
#10 
[10,20,30,12],
[36,87,98,18]
[21,24,29,25]
[44,33,22,10]
[36,42,88,70]
bundan 2 dim array yarat 
sonra 
[33,22,10]
[42,88,70]
bele output verecek kod yaz
sonra 
[24,29]
[33,22]
bele output verecek kod yaz

[70]
bele output verecek kod yaz

In [61]:
arr = np.array([
    [10, 20, 30, 12],
    [36, 87, 98, 18],
    [21, 24, 29, 25],
    [44, 33, 22, 10],
    [36, 42, 88, 70]
])
print(arr)

[[10 20 30 12]
 [36 87 98 18]
 [21 24 29 25]
 [44 33 22 10]
 [36 42 88 70]]


In [62]:
arr_1 = arr[3:5,1:4]
print(arr_1)

[[33 22 10]
 [42 88 70]]


In [63]:
arr_2 = arr[2:4,1:3]
print(arr_2)

[[24 29]
 [33 22]]


In [64]:
arr_3 = arr[4,3:4]
print(arr_3)

[70]
